name: just some test
on:
  push:
    branches:
      - feature/*

jobs:
  test-stack:
    name: test stack
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
     - name: Run a one-line script
        run: echo Hello, world!
